---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastembed-server
  namespace: qdrant
spec:
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 100%
  minReadySeconds: 90
  selector:
    matchLabels:
      app: fastembed-server
  template:
    metadata:
      labels:
        app: fastembed-server
      annotations:
        instrumentation.opentelemetry.io/inject-python: opentelemetry-operator/elastic-instrumentation
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: node
                    operator: In
                    values:
                      - service
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - fastembed-server
                topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 60
      containers:
        - name: fastembed-server
          image: artifact.nc.rdcloud.4c.hq.cmcc:80/znm-docker-dev/qdrant/fastembed-server:v1.9.0
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: "2Gi"
              cpu: "4000m"
            limits:
              memory: "2Gi"
              cpu: "4000m"
          ports:
            - containerPort: 8000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: "health"
              port: 8000
            initialDelaySeconds: 30
            failureThreshold: 3
            periodSeconds: 5
            timeoutSeconds: 5
          env:
            - name: EMBED_MODEL_NAME
              value: "BAAI/bge-small-zh-v1.5"
            - name: EMBED_THREADS
              valueFrom:
                resourceFieldRef:
                  containerName: fastembed-server
                  resource: limits.cpu
                  divisor: "1"
            - name: MEM_LIMIT_GB
              valueFrom:
                resourceFieldRef:
                  containerName: fastembed-server
                  resource: limits.memory
                  divisor: "1Gi"
---
apiVersion: v1
kind: Service
metadata:
  name: fastembed-server
  namespace: qdrant
spec:
  type: ClusterIP
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: fastembed-server
